GEMINI_API_KEY_ENV = "GEMINI_API_KEY"
GEMINI_ROBOTICS_ER_MODEL_ENV = "GEMINI_ROBOTICS_ER_MODEL"
GEMINI_ROBOTICS_ER_THINKING_BUDGET_ENV = "GEMINI_ROBOTICS_ER_THINKING_BUDGET"
GEMINI_ROBOTICS_ER_TIMEOUT_MILLISECONDS_ENV = (
    "GEMINI_ROBOTICS_ER_TIMEOUT_MILLISECONDS"
)
DEFAULT_GEMINI_ROBOTICS_ER_MODEL = "gemini-robotics-er-1.6-preview"
DEFAULT_GEMINI_ROBOTICS_ER_TIMEOUT_MILLISECONDS = 30_000
