/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/demo-replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Demo Replay
         * @description Return the controlled replay for the primary operations view.
         */
        get: operations["get_demo_replay_api_demo_replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Return backend readiness.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Observations */
        get: operations["stream_observations_api_observations_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}/approve-alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Alert */
        post: operations["approve_alert_api_incidents__incident_id__approve_alert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}/verify-clearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Clearance */
        post: operations["verify_clearance_api_incidents__incident_id__verify_clearance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}/audit-packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Packet */
        get: operations["get_audit_packet_api_incidents__incident_id__audit_packet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product Contract
         * @description Return the shared product contract catalog.
         */
        get: operations["get_product_contract_api_product_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertEvent
         * @description Human-approved alert transcript record.
         */
        AlertEvent: {
            /** Incident Id */
            incident_id: string;
            /** Approval Actor */
            approval_actor: string;
            /** Alert Text */
            alert_text: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * ApproveAlertRequest
         * @description Human alert approval command.
         */
        ApproveAlertRequest: {
            /** Approval Actor */
            approval_actor: string;
            /**
             * Decision
             * @constant
             */
            decision: "approved";
            /** Alert Text */
            alert_text: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /**
         * AuditPacket
         * @description Closed incident evidence package.
         */
        AuditPacket: {
            /** Incident Id */
            incident_id: string;
            /** Before Frame Id */
            before_frame_id: string;
            /** After Frame Id */
            after_frame_id: string;
            /**
             * Before Timestamp
             * Format: date-time
             */
            before_timestamp: string;
            /**
             * After Timestamp
             * Format: date-time
             */
            after_timestamp: string;
            /** Alert Transcript */
            alert_transcript: string;
            verification_verdict: components["schemas"]["VerificationVerdict"];
        };
        /**
         * ClearanceVerification
         * @description Before/after visual clearance verification record.
         */
        ClearanceVerification: {
            verdict: components["schemas"]["VerificationVerdict"];
            /** Confidence */
            confidence: number;
            /** Rationale */
            rationale: string;
            /** After Evidence Frame Id */
            after_evidence_frame_id: string;
        };
        /**
         * ClearanceVerificationResponse
         * @description Result for a clearance verification command.
         */
        ClearanceVerificationResponse: {
            /** Incident Id */
            incident_id: string;
            state: components["schemas"]["IncidentState"];
            verification: components["schemas"]["ClearanceVerification"];
        };
        /**
         * CriticalZone
         * @description Site-defined physical area monitored for safety violations.
         */
        CriticalZone: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            zone_type: components["schemas"]["ZoneType"];
            /** Geometry */
            geometry: components["schemas"]["ZonePoint"][];
            policy: components["schemas"]["CriticalZonePolicy"];
        };
        /**
         * CriticalZonePolicy
         * @description Policy controlling when observations become incidents.
         */
        CriticalZonePolicy: {
            /** Dwell Threshold Seconds */
            dwell_threshold_seconds: number;
            severity: components["schemas"]["Severity"];
            /** Escalation Channel */
            escalation_channel: string;
        };
        /**
         * DemoReplay
         * @description Controlled replay source for the primary robotics supervision demo.
         */
        DemoReplay: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            zone: components["schemas"]["CriticalZone"];
            timing: components["schemas"]["DemoTiming"];
            /** Frames */
            frames: components["schemas"]["ReplayFrame"][];
        };
        /**
         * DemoTiming
         * @description Replay timing options that do not change lifecycle states.
         */
        DemoTiming: {
            default_mode: components["schemas"]["DemoTimingMode"];
            /** Options */
            options: components["schemas"]["DemoTimingOption"][];
        };
        /**
         * DemoTimingMode
         * @description Demo replay pacing modes.
         * @enum {string}
         */
        DemoTimingMode: "stage" | "real_time";
        /**
         * DemoTimingOption
         * @description Single replay pacing option for demo controls.
         */
        DemoTimingOption: {
            mode: components["schemas"]["DemoTimingMode"];
            /** Label */
            label: string;
            /** Frame Interval Ms */
            frame_interval_ms: number;
            /** Playback Dwell Seconds */
            playback_dwell_seconds: number;
            /** Playback Clearance Seconds */
            playback_clearance_seconds: number;
            /** Requires External Providers */
            requires_external_providers: boolean;
        };
        /**
         * EvidenceAnnotation
         * @description Label attached to an evidence frame.
         */
        EvidenceAnnotation: {
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * EvidenceFrame
         * @description Frame or image reference supporting an observation or incident.
         */
        EvidenceFrame: {
            /** Id */
            id: string;
            source: components["schemas"]["EvidenceSource"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Image Ref */
            image_ref: string;
            /** Annotations */
            annotations?: components["schemas"]["EvidenceAnnotation"][];
        };
        /**
         * EvidenceSource
         * @description Evidence frame source categories.
         * @enum {string}
         */
        EvidenceSource: "camera" | "replay" | "uploaded_image" | "generated_test_frame";
        /**
         * ExportStatus
         * @description Review/export availability states.
         * @enum {string}
         */
        ExportStatus: "local_only" | "export_pending" | "exported" | "export_unavailable";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Backend readiness response.
         */
        HealthResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "ready";
            /** Version */
            version: string;
        };
        /**
         * IncidentCommandResponse
         * @description Result for incident state-changing commands.
         */
        IncidentCommandResponse: {
            /** Incident Id */
            incident_id: string;
            state: components["schemas"]["IncidentState"];
            alert_event?: components["schemas"]["AlertEvent"] | null;
        };
        /**
         * IncidentDetail
         * @description Incident snapshot for the detail panel.
         */
        IncidentDetail: {
            /** Incident Id */
            incident_id: string;
            state: components["schemas"]["IncidentState"];
            incident_report?: components["schemas"]["IncidentReport"] | null;
            severity: components["schemas"]["Severity"];
            /** Recommendation */
            recommendation: string;
            latest_observation: components["schemas"]["Observation"];
        };
        /**
         * IncidentReport
         * @description Structured explanation generated for an opened incident.
         */
        IncidentReport: {
            /** Hazard */
            hazard: string;
            severity: components["schemas"]["Severity"];
            /** Evidence Summary */
            evidence_summary: string;
            /** Rationale */
            rationale: string;
            /** Recommended Action */
            recommended_action: string;
            /** Alert Text Candidate */
            alert_text_candidate: string;
        };
        /**
         * IncidentState
         * @description Policy-controlled safety incident lifecycle states.
         * @enum {string}
         */
        IncidentState: "clear" | "dwell" | "incident_open" | "alert_pending" | "alert_broadcast" | "clearing" | "verified_clear" | "closed" | "uncertain";
        /**
         * Observation
         * @description Evidence-backed critical-zone observation.
         */
        Observation: {
            /** Zone Id */
            zone_id: string;
            observed_state: components["schemas"]["ObservedState"];
            /** Dwell Duration Seconds */
            dwell_duration_seconds: number;
            /** Evidence Frame Id */
            evidence_frame_id: string;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * ObservationAssessment
         * @description Policy assessment for a critical-zone observation.
         */
        ObservationAssessment: {
            incident_state: components["schemas"]["IncidentState"];
            /** Policy Reason */
            policy_reason: string;
            incident?: components["schemas"]["SafetyIncident"] | null;
        };
        /**
         * ObservedState
         * @description Observed state of a monitored critical zone.
         * @enum {string}
         */
        ObservedState: "clear" | "blocked" | "uncertain" | "camera_unavailable";
        /**
         * ProductContract
         * @description Contract catalog shared with the frontend.
         */
        ProductContract: {
            /**
             * Primary Workflow
             * @constant
             */
            primary_workflow: "robot_workcell_obstruction";
            /** Observation States */
            observation_states: components["schemas"]["ObservedState"][];
            /** Incident States */
            incident_states: components["schemas"]["IncidentState"][];
            /** Severity Levels */
            severity_levels: components["schemas"]["Severity"][];
            /** Zone Types */
            zone_types: components["schemas"]["ZoneType"][];
            /** Provider Boundaries */
            provider_boundaries: components["schemas"]["ProviderBoundary"][];
            /** Review Export Provider Statuses */
            review_export_provider_statuses: components["schemas"]["ReviewExportProviderStatus"][];
            /** Provider Integration Statuses */
            provider_integration_statuses: components["schemas"]["ProviderIntegrationStatus"][];
            reference_zone: components["schemas"]["CriticalZone"];
            reference_evidence_frame: components["schemas"]["EvidenceFrame"];
            reference_observation: components["schemas"]["Observation"];
            reference_incident: components["schemas"]["SafetyIncident"];
        };
        /**
         * ProviderAvailability
         * @description Provider availability and configuration state.
         * @enum {string}
         */
        ProviderAvailability: "available" | "configured" | "unconfigured";
        /**
         * ProviderBoundary
         * @description Backend-only integration boundaries.
         * @enum {string}
         */
        ProviderBoundary: "perception" | "incident_reporting" | "verification" | "review_export";
        /**
         * ProviderIntegration
         * @description Concrete provider integrations exposed for demo readiness.
         * @enum {string}
         */
        ProviderIntegration: "local_replay" | "runpod_yolo" | "local_incident_report" | "openai_foundry" | "local_clearance" | "gemini_robotics_er" | "local_review" | "encord";
        /**
         * ProviderIntegrationStatus
         * @description Readiness status for a concrete provider integration.
         */
        ProviderIntegrationStatus: {
            provider: components["schemas"]["ProviderIntegration"];
            boundary: components["schemas"]["ProviderBoundary"];
            availability: components["schemas"]["ProviderAvailability"];
            /** Detail */
            detail: string;
        };
        /**
         * ReplayFrame
         * @description Single replay frame paired with its critical-zone observation.
         */
        ReplayFrame: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            evidence_frame: components["schemas"]["EvidenceFrame"];
            observation: components["schemas"]["Observation"];
            assessment: components["schemas"]["ObservationAssessment"];
        };
        /**
         * ReviewDecision
         * @description Human review decisions for evidence samples.
         * @enum {string}
         */
        ReviewDecision: "accepted" | "corrected" | "rejected" | "pending";
        /**
         * ReviewExportProvider
         * @description Review export destinations exposed to product code.
         * @enum {string}
         */
        ReviewExportProvider: "local_review" | "encord";
        /**
         * ReviewExportProviderStatus
         * @description Availability status for a review/eval destination.
         */
        ReviewExportProviderStatus: {
            provider: components["schemas"]["ReviewExportProvider"];
            availability: components["schemas"]["ProviderAvailability"];
            /** Detail */
            detail: string;
        };
        /**
         * ReviewSample
         * @description Review/eval sample produced from a closed incident.
         */
        ReviewSample: {
            /** Incident Id */
            incident_id: string;
            /** Before Frame Id */
            before_frame_id: string;
            /** After Frame Id */
            after_frame_id: string;
            /** Labels */
            labels: string[];
            human_decision: components["schemas"]["ReviewDecision"];
            export_status: components["schemas"]["ExportStatus"];
        };
        /**
         * SafetyIncident
         * @description Operational record for a critical-zone safety violation.
         */
        SafetyIncident: {
            /** Id */
            id: string;
            /** Zone Id */
            zone_id: string;
            state: components["schemas"]["IncidentState"];
            severity: components["schemas"]["Severity"];
            /** Before Evidence Frame Id */
            before_evidence_frame_id: string;
            incident_report?: components["schemas"]["IncidentReport"] | null;
            /** Alert Events */
            alert_events?: components["schemas"]["AlertEvent"][];
            verification?: components["schemas"]["ClearanceVerification"] | null;
            audit_packet?: components["schemas"]["AuditPacket"] | null;
            review_sample?: components["schemas"]["ReviewSample"] | null;
        };
        /**
         * Severity
         * @description Incident severity levels.
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationVerdict
         * @description Clearance verification verdicts.
         * @enum {string}
         */
        VerificationVerdict: "clear" | "still_blocked" | "uncertain";
        /**
         * ZonePoint
         * @description Normalized image coordinate for a zone polygon.
         */
        ZonePoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * ZoneType
         * @description Supported critical-zone categories.
         * @enum {string}
         */
        ZoneType: "emergency_exit" | "walkway" | "forklift_lane" | "robot_workcell";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_demo_replay_api_demo_replay_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoReplay"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stream_observations_api_observations_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent observation event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    get_incident_api_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_alert_api_incidents__incident_id__approve_alert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentCommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_clearance_api_incidents__incident_id__verify_clearance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearanceVerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_packet_api_incidents__incident_id__audit_packet_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPacket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_contract_api_product_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductContract"];
                };
            };
        };
    };
}
