from typing import Literal

from pydantic import Field

from sitewalk.contracts import ContractModel

EncordShape = Literal["bounding_box", "polygon"]
EncordClassificationKind = Literal["radio", "text"]


class EncordOntologyObject(ContractModel):
    """Object type that should exist in the Encord ontology."""

    name: str = Field(min_length=1)
    shape: EncordShape
    description: str


class EncordOntologyClassification(ContractModel):
    """Classification type that should exist in the Encord ontology."""

    name: str = Field(min_length=1)
    kind: EncordClassificationKind
    description: str
    options: list[str] = Field(default_factory=list)


class EncordOntologySpec(ContractModel):
    """Source-of-truth ontology expected by the incident export pipeline."""

    title: str
    description: str
    objects: list[EncordOntologyObject]
    classifications: list[EncordOntologyClassification]


def build_robot_safety_ontology_spec() -> EncordOntologySpec:
    """Return the review ontology used for robot obstruction incidents."""
    return EncordOntologySpec(
        title="AIRW Robot Safety Incident Ontology",
        description=(
            "Labels before/after robot safety incidents so Encord can become the "
            "review dataset for obstruction handling, approvals, and clearance."
        ),
        objects=[
            EncordOntologyObject(
                name="robot_path",
                shape="polygon",
                description="The planned or protected robot travel area.",
            ),
            EncordOntologyObject(
                name="obstruction",
                shape="bounding_box",
                description="An object occupying the robot path or safety zone.",
            ),
            EncordOntologyObject(
                name="safe_drop_zone",
                shape="polygon",
                description="A safe area where a removable obstruction can be placed.",
            ),
            EncordOntologyObject(
                name="human",
                shape="bounding_box",
                description="A person in or near the robot workspace.",
            ),
            EncordOntologyObject(
                name="robot",
                shape="bounding_box",
                description="The robot or end effector visible in the scene.",
            ),
        ],
        classifications=[
            EncordOntologyClassification(
                name="zone_state",
                kind="radio",
                description="Whether the protected path or zone is blocked.",
                options=["clear", "blocked", "uncertain"],
            ),
            EncordOntologyClassification(
                name="approval_state",
                kind="radio",
                description="Human operator decision before robot intervention.",
                options=["pending", "approved", "rejected"],
            ),
            EncordOntologyClassification(
                name="robot_action",
                kind="radio",
                description="Action selected for the robot or operator.",
                options=[
                    "none",
                    "stopped",
                    "remove_obstruction",
                    "manual_intervention",
                ],
            ),
            EncordOntologyClassification(
                name="verification_result",
                kind="radio",
                description="Before/after outcome after attempted clearance.",
                options=["cleared", "still_blocked", "unsafe", "uncertain"],
            ),
            EncordOntologyClassification(
                name="review_decision",
                kind="radio",
                description="Human review result for the exported sample.",
                options=["accepted", "corrected", "rejected", "pending"],
            ),
            EncordOntologyClassification(
                name="incident_id",
                kind="text",
                description="Source application incident identifier.",
            ),
            EncordOntologyClassification(
                name="openai_outcome_summary",
                kind="text",
                description="Short structured outcome summary generated by OpenAI.",
            ),
        ],
    )
